spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jupiter?Unicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  servlet:
    context-path: /Jupiter
  port: 8080
#logging:
#  level:
#    root: debug
#    com.uzumaki.jupiter: debug
